# Generated by Django 3.1.2 on 2020-10-22 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('get_cntnt', '0002_news_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pub_date',
            new_name='pub_time',
        ),
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
