# Generated by Django 3.0.4 on 2020-10-26 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('get_cntnt', '0003_auto_20201022_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='time published'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
