# Generated by Django 3.1.2 on 2020-10-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_cntnt', '0004_auto_20201026_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='snippet',
            field=models.CharField(default='Новость недоступна для просмотра', max_length=200),
        ),
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.CharField(choices=[('tech', 'Технологии'), ('sport', 'Спорт'), ('politics', 'Политика'), ('entertainment', 'Развлечения'), ('lifestyle', 'Образ жизни'), ('business', 'Бизнес'), ('science', 'Наука')], default='lifestyle', max_length=20),
        ),
    ]
