# Generated by Django 3.1.2 on 2020-10-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_cntnt', '0005_auto_20201027_2038'),
        ('get_cntnt', '0005_auto_20201027_2207'),
    ]

    operations = [
    ]
