# Generated by Django 3.1.2 on 2020-11-12 17:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get_cntnt', '0007_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Favourite',
        ),
    ]
