# Generated by Django 3.1.2 on 2020-11-16 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('get_cntnt', '0008_auto_20201112_2029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favourite',
            new_name='Profile',
        ),
    ]
