# Generated by Django 3.1.2 on 2020-11-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_cntnt', '0010_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='love_list',
            field=models.ManyToManyField(to='get_cntnt.Source'),
        ),
    ]
