# Generated by Django 3.1.2 on 2020-11-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_cntnt', '0013_auto_20201122_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='url_rss',
            new_name='rss',
        ),
    ]
