# Generated by Django 3.1.2 on 2020-11-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_cntnt', '0014_auto_20201122_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='rss',
            field=models.URLField(default='Нет rss ленты'),
        ),
    ]
