# Generated by Django 3.1.2 on 2020-11-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_cntnt', '0015_auto_20201122_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='rss',
        ),
        migrations.AddField(
            model_name='source',
            name='url_valid',
            field=models.URLField(default='asd'),
            preserve_default=False,
        ),
    ]
