# Generated by Django 3.1.2 on 2020-11-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_cntnt', '0016_auto_20201122_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='url_valid',
            new_name='rss',
        ),
    ]
